version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - gcp-creds:/creds
      - .:/app
    working_dir: /app
    environment:
      - CLOUDSDK_CONFIG=/creds
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  gcp-creds:

