services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hpfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./static:/static
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hpfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
    depends_on:
      - db